name: Continuous Integration

on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        os: [ 'macos-latest', 'ubuntu-16.04' ]
        go: [ '1.13' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - run: gofmt 2>&1

      - run: go build -v .

      - run: go test ./...
